apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
- gatakko-core/haproxy.cm.yaml
- gatakko-core/haproxy.ds.yaml
- gatakko-core/haproxy.svc.yaml
patches:
- path: gatakko-user/lightdm.svc.patch.yaml
- path: gatakko-user/sshd.svc.patch.yaml
- path: gatakko-user/xrdp.svc.patch.yaml
