apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patches:
- target:
    name: (ldap.*|phpldapadmin.*)
    namespace: gatakko-core
  patch: |
    apiVersion: any
    kind: any
    metadata:
      name: any
    $patch: delete
