apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- admin.role.yaml
- admin.rolebinding.yaml
- admin.sa.yaml
- admin.secret.yaml
- apt-proxy-init.cm.yaml
- apt-proxy.deploy.yaml
- apt-proxy.pvc.yaml
- apt-proxy.secret.yaml
- apt-proxy.svc.yaml
- cacert.secret.yaml
- daily-script.cm.yaml
- daily.cronjob.yaml
- git-host-key.secret.yaml
- git-init.cm.yaml
- git-msmtprc.secret.yaml
- git-script.cm.yaml
- git.deploy.yaml
- git.pvc.yaml
- git.sa.yaml
- git.secret.yaml
- git.svc.yaml
- ldap-env.cm.yaml
- ldap-env.secret.yaml
- ldap-init.cm.yaml
- ldap.deploy.yaml
- ldap.pvc.yaml
- ldap.secret.yaml
- ldap.svc.yaml
- gatakko-core.ns.yaml
- phpldapadmin-init.cm.yaml
- phpldapadmin.deploy.yaml
- phpldapadmin.secret.yaml
- phpldapadmin.svc.yaml
- regcred.secret.yaml
- registry.deploy.yaml
- registry.pvc.yaml
- registry.secret.yaml
- registry.svc.yaml
- sssd-init.cm.yaml
- sssd.ds.yaml
- syslogd-init.cm.yaml
- syslogd.deploy.yaml
- syslogd.pvc.yaml
- syslogd.svc.yaml
- webui-init.cm.yaml
- webui-ssh.secret.yaml
- webui.deploy.yaml
- webui.secret.yaml
- webui.svc.yaml
